version: '3.9'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/controle-hctco
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 040906
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: controle-hctco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 040906
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: